package com.hldj.hmyg.DaoBean.SaveJson;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hldj.hmyg.DaoBean.SaveJson.SavaBean;

import com.hldj.hmyg.DaoBean.SaveJson.SavaBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig savaBeanDaoConfig;

    private final SavaBeanDao savaBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        savaBeanDaoConfig = daoConfigMap.get(SavaBeanDao.class).clone();
        savaBeanDaoConfig.initIdentityScope(type);

        savaBeanDao = new SavaBeanDao(savaBeanDaoConfig, this);

        registerDao(SavaBean.class, savaBeanDao);
    }
    
    public void clear() {
        savaBeanDaoConfig.clearIdentityScope();
    }

    public SavaBeanDao getSavaBeanDao() {
        return savaBeanDao;
    }

}
